name: CI Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  ALLURE_RESULTS_DIR: allure-results

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run test:unit

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-results
          path: allure-results/


  api-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Start server
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - run: npm run test:api

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-results
          path: allure-results/


  ui-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npx playwright install --with-deps



      - run: npm run test:ui

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-results
          path: playwright-report/


  allure-report:
    runs-on: ubuntu-latest
    needs: [ unit-tests, api-tests, ui-tests ]
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      # 🔥 ВАЖНО: берём ВСЕ allure-results из вложенных папок
      - name: Collect Allure results
        run: |
          mkdir -p allure-results
          find artifacts -type f -name "*-result.json" -exec cp {} allure-results/ \;
          find artifacts -type f -name "*.json" -exec cp {} allure-results/ \;

      - name: Show collected results (debug)
        run: ls -R allure-results

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  notify:
    runs-on: ubuntu-latest
    needs: [ allure-report ]
    if: always()

    steps:
      - name: Telegram notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          token: ${{ secrets.TG_TOKEN }}
          to: ${{ secrets.TG_CHAT_ID }}
          message: |
            📊 CI Pipeline finished
            Status: ${{ needs.allure-report.result }}
            Repo: ${{ github.repository }}
            Branch: ${{ github.ref_name }}  


  deploy-report:
    runs-on: ubuntu-latest
    needs: allure-report

    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: report/

      - name: Debug
        run: ls -R report/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report